apiVersion: v1
kind: Service
metadata:
  name:  mockoptimizefundsservice-svc
  labels:
    app: mockoptimizefundsservice
spec:
  selector:
    app:  mockoptimizefundsservice
  type: NodePort
  ports:
   - port:  3005
     nodePort: 30005
     protocol: TCP