apiVersion: v1
kind: ReplicationController
metadata:
  name: mockoptimizefundsservice-rc
spec:
  replicas: 5
  selector:
    app: mockoptimizefundsservice
  template:
    metadata:
      labels:
        app: mockoptimizefundsservice
    spec:
      containers:
        - name: hello-ctr
          image: optimateam/lbgpoc_mockoptimizefundsservice:latest
          ports:
            - containerPort: 3005